name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc: ['8.8', '8.10', '9.0', '9.2', '9.4', '9.6', '9.8']
        include:
          - os: macOS-latest
            ghc: '9.4'
          - os: macOS-latest
            ghc: '9.6'
          - os: macOS-latest
            ghc: '9.8'
          - os: windows-latest
            ghc: '9.4'
          - os: windows-latest
            ghc: '9.6'
          - os: windows-latest
            ghc: '9.8'
    steps:
    - uses: actions/checkout@v4


    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get -y update
        sudo apt-get -y install libtinfo5 libtinfo6 libncurses5 libncurses6

    - if: runner.os != 'Windows'
      name: Setup toolchain
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_INSTALL_NO_STACK=1 BOOTSTRAP_HASKELL_GHC_VERSION=${{ matrix.ghc }} BOOTSTRAP_HASKELL_ADJUST_BASHRC=yes sh

    - name: Build
      run: |
        set -eux
        [ -e ~/.ghcup/env ] && . ~/.ghcup/env
        ghcup install ghc --set ${{ matrix.ghc }}
        echo ${{ matrix.ghc }}
        echo $(ghc --numeric-version)
        cabal update
        cabal configure --enable-tests --test-show-details=direct
        cabal build
        cabal test
        cabal haddock
        cabal check
        cabal sdist
      shell: bash

  i386:
    runs-on: ubuntu-latest
    container:
      image: i386/ubuntu:bionic
    steps:
    - name: Install
      run: |
        apt-get update -y
        apt-get install -y autoconf build-essential zlib1g-dev libgmp-dev curl libncurses5 libtinfo5 libncurses5-dev libtinfo-dev
        curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_INSTALL_NO_STACK=1 sh
    - uses: actions/checkout@v1
    - name: Test
      run: |
        . ~/.ghcup/env
        cabal update
        cabal test --test-show-details=direct

